### ISSUE TITLE
network interface names are limited to 15 characters

### ISSUE THREAD

**Issue by mazerty** [zebr0/zebr0-conf#4]
when creating lxd-compose stack for project demovaadin8, i encountered the following error:
```
creating /1.0/networks demovaadin8master0
Traceback (most recent call last):
  File "/usr/bin/lxd-compose", line 169, in <module>
    globals()[args.command]()
  File "/usr/bin/lxd-compose", line 110, in create
    Network(item).create()
  File "/usr/bin/lxd-compose", line 42, in create
    session.post(self.get_full_collection_url(), json=self._config)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/bin/lxd-compose", line 145, in hook
    raise Exception(json)
Exception: {'error': 'Interface name is too long (maximum 15 characters)', 'error_code': 400, 'type': 'error'}
```
find a way to prevent that

**Comment by mazerty** [comment]
the best way would be to add a variable, but it would be good to be able to revert to the "default" name "{{ project }}{{ stage }}0" when this variable isn't set for the project... i don't know if i can do that with jinja...

**Comment by mazerty** [comment]
{{ "network-name" | lookup | default(project ~ stage ~ 0 }} would work if i changed the code in zebr0-core not to throw an exception if there's no value for a key...

**Comment by mazerty** [comment]
managed to make it work in zebr0-template, commit soon

**Comment by mazerty** [comment]
but that's not enough...
one doesn't want to have to commit a special network name for his branch if its name is so long...
so
since what we want is a unique network name for any combination of project + stage, what i'll do is i'll hash the combination, truncate it to 14 characters and append '0'
